<?php

?>
<div class="popup-container">
  <div class="modal">
    <div class="header">
      <button class="close-btn">x</button>
    </div>
    <div class="content">
      <div class="image-container">
      <img src="<?php echo $this->getViewFileUrl('PopupModule_Popup::images/pop-up-image.jpg'); ?>" />
      </div>
      <div class="text-container">
        <p>Enter your name below to be in with the chance of winning a stylish Drinks Trolly</p>
        <span class="error-message"></span>
        <input type="text" name="name" class="input" placeholder="Enter your name..." />
        <button class="submit-btn">Submit</button>
      </div>
    </div>
  </div>
  <div class="modal-overlay">

  </div>
</div>
<div class="message-container"></div>
